<div class="row-fluid">
    <div class="span4"></div>
    <div class="span4">
        <center><h2>Contacte</h2></center>
        <form action="/contacte/ok" class="form" method="POST">
            <table class="table" style="border:0; margin:auto;">
                <tr>
                    <div class="form-item">
                        <td>
                            <span>Nom: </span>
                        </td>
                        <td>
                            <input type="text" maxlength="20" name="nom" id="nom" class="form-text required" required />
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-item">
                        <td>
                            <span>Email: </span>
                        </td>
                        <td>
                            <input type="email" maxlength="20" name="email" id="nom" class="form-text required" required />
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-item">
                        <td>
                            <span>Assumpte: </span>
                        </td>
                        <td>
                            <input type="text" maxlength="20" name="assumpte" id="nom" class="form-text required" required />
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-item">
                        <td>
                            <span>Missatge: </span>
                        </td>
                        <td>
                            <textarea cols="60" rows="5" name="missatge" id="edit-message"  class="form-textarea resizable required" required ></textarea>
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-item">
                        <td></td>
                        <td>
                            <button type="submit" class="btn submit">Envia</button>
                        </td>
                    </div>
                </tr>
            </table>
        </form>
    </div>
    <div class="span4"></div>
</div>