<div class="row-fluid">
    <div class="span4"></div>
    <div class="span4">
        <center><h2>Conferencies</h2></center>
        <form action="/conferencies/add" class="form" method="POST">
            <table class="table" style="border:0; margin:auto;">
                <tr>
                    <div class="form-item">
                        <td>
                            <span>Ponent: </span>
                        </td>
                        <td>
                            <input type="text" maxlength="20" name="ponent" id="nom" class="form-text required" required />
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-item">
                        <td>
                            <span>Data: </span>
                        </td>
                        <td>
                            <input type="date" maxlength="20" name="data" min="<?php echo date('Y-m') . '-' . (date('d')+1); ?>" id="nom" class="form-text required" required />
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-item">
                        <td>
                            <span>Durada (min): </span>
                        </td>
                        <td>
                            <input type="number" maxlength="20" name="durada" id="nom" class="form-text required" required />
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-item">
                        <td>
                            <span>Tema: </span>
                        </td>
                        <td>
                            <input type="text" maxlength="20" name="tema" id="nom" class="form-text required" required />
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-item">
                        <td></td>
                        <td>
                            <button type="submit" class="btn submit">Comfirma</button>
                        </td>
                    </div>
                </tr>
            </table>
        </form>
    </div>
    <div class="span4"></div>
</div>